#This script contains examples of the commands from Entrez direct - command line access to NCBI

# 1) getting the run accessions (SRR-s) for a list of project accessions (PRJNA-s) in a loop (shown to be slow)
input="/home/vlad/SRA_project/bioproject_result_6k.txt" # file containing project accessions each in new row
while read line <&3
do
  esearch -db sra -query "$line" | efetch --format runinfo |cut -d "," -f 1 
done 3<"$input" >PRJNA_search_results_loop.txt 

input="/home/vlad/SRA_project/bioproject_result_100.txt"
time while read line <&3
do
  esearch -db sra -query "$line" | efetch --format runinfo |cut -d "," -f 1 
done 3<"$input"





# 2) Another way to obtain SRR from projects: merge all PRJNA with " OR " and pass as a querry to esearch:
#query of PRJNAs separated by "OR" must be made by script_R_1_PRJNA_convert.R
cd /home/vlad/SRA_project/ncbi_search_results
l=$(<PRJNA_converted.txt)
time esearch -db sra -query "$l" | efetch --format runinfo |cut -d "," -f 1 > PRJNA_search_results_5k_no_transcr.txt

# 3) obtain Runinfo for list of SRRs (needed to obtain and plot filesizes of metadata-filtered samples)
cd /home/vlad/SRA_project/ncbi_search_results
l=$(<Intersect_converted.txt)
time esearch -db sra -query "$l" | efetch --format runinfo > Intersect_SraAccList_13k_no_transcr.txt_PRJNA_search_results_5k_no_transcr_RUNINFO.csv


# 4) Frgmented looped way to obtain SRRs for PRJNAs
#problem is that esearch has a limit for query string length, and when it's too many PRJNAs, throws an error
# To overcome this, we can instead create several queries with 5000 PRJNAs in each, for example
# So, here we run in a loop for partial queries from fragment files, also generated by script_R_1_PRJNA_convert.R

cd /home/vlad/SRA_project/ncbi_search_results
touch PRJNA_search_results_16k_no_transcr.txt
for i in PRJNA_converted_16k_no_transcr_fragment_*.txt; do
    [ -f "$i" ] || break
    l=$(<$i)
    echo starting $i
    time esearch -db sra -query "$l" | efetch --format runinfo |cut -d "," -f 1 >> PRJNA_search_results_16k_no_transcr.txt
done
